services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  app:
    image: weather
    container_name: weather-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_DRIVER: org.postgresql.Driver
      OPENWEATHER_API: 7fc689b71c81bd1a2c74384cd158bdce
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge