services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  app:
    image: weather
    container_name: weather-app
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_DRIVER: org.postgresql.Driver
      OPENWEATHER_API: ${OPENWEATHER_API}
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge